List products = [
  {
    "id": 1,
    "title": "Orange",
    "description": "The orange is a usually round or oval citrus; its rind and flesh are generally orange, except the varieties of red pulp. The edible part of the orange is the flesh, consumed in fresh or in juice.",
    "price": 10,
    "discountPercentage": 25,
    "rating": 4.5,
    "stock": 100,
    "category": "Fruits",
    "thumbnail": "assets/orange.png",
    "images": [
      "assets/orange.png",
      "assets/orange.png",     
      "assets/orange.png",     
      "assets/orange.png",     
],
    "favourite": false,
  },
    {
    "id": 2,
    "title": "Apple",
    "description": "Apples are among the world's most popular fruits. They grow on the apple tree (Malus domestica), originally from Central Asia. Apples are high in fiber, vitamin C, and various antioxidants.",
    "price": 15,
    "discountPercentage": 15,
    "rating": 4.5,
    "stock": 95,
    "category": "Fruits",
    "thumbnail": "assets/apple.jpg",
    "images": [
      "assets/apple.jpg",
      "assets/apple.jpg",
      "assets/apple.jpg",
      "assets/apple.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 3,
    "title": "Mango",
    "description": "The immature fruit has green skin that gradually turns yellow, orange, purple, red, or combinations of these colors as the fruit matures. Mature fruit has a characteristic fragrance and a smooth, thin, tough skin. The flesh of ripe mangos is pale yellow to orange. The flesh is juicy, sweet, and sometimes fibrous.",
    "price": 30,
    "discountPercentage": 05,
    "rating": 4.5,
    "stock": 95,
    "category": "Fruits",
    "thumbnail": "assets/mango.png",
    "images": [
      "assets/mango.png",
      "assets/mango.png",
      "assets/mango.png",
      "assets/mango.png",
    ],
    "favourite": false,
  },
  {
    "id": 4,
    "title": "Banana",
    "description": "Bananas are a healthy source of fiber, potassium, vitamin B6, vitamin C, and various antioxidants and phytonutrients.",
    "price": 280,
    "discountPercentage": 17.91,
    "rating": 4.3,
    "stock": 123,
    "category": "Fruits",
    "thumbnail": "assets/banana.jpg",
    "images": [
      "assets/banana.jpg",
      "assets/banana.jpg",
      "assets/banana.jpg",
      "assets/banana.jpg",
      "assets/banana.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 5,
    "title": "Peach",
    "description":
        "Peaches are a fuzzy fruit native to northwest China. They are a member of the stone fruit family, which means that their flesh surrounds one large middle seed",
    "price": 499,
    "discountPercentage": 10.58,
    "rating": 4.09,
    "stock": 32,
    "category": "Fruits",
    "thumbnail": "assets/peach.jpg",
    "images": [
      "assets/peach.jpg",
      "assets/peach.jpg",
      "assets/peach.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 6,
    "title": "Potato",
    "description":
        " The potato is one of some 150 tuber-bearing species of the genus Solanum (a tuber is the swollen end of an underground stem)",
    "price": 12,
    "discountPercentage": 11.02,
    "rating": 4.57,
    "stock": 83,
    "category": "Vegetables",
    "thumbnail": "assets/patoto.webp",
    "images": [
      "assets/patoto.webp",
      "assets/patoto.webp",
      "assets/patoto.webp",
      "assets/patoto.webp",
    ],
    "favourite": false,
  },
  {
    "id": 7,
    "title": "Onion",
    "description":
        "Onions belong to the Allium family of plants, which also includes chives, garlic, and leeks.",
    "price": 14,
    "discountPercentage": 4.15,
    "rating": 4.25,
    "stock": 354,
    "category": "Vegetables",
    "thumbnail": "assets/onion.webp",
    "images": [
      "assets/onion.webp",
      "assets/onion.webp",
      "assets/onion.webp",
      "assets/onion.webp",
    ],
    "favourite": false,
  },
  {
    "id": 8,
    "title": "Carrot",
    "description":
        "Raw carrots are 88% water, 9% carbohydrates, 0.9% protein, 2.8% dietary fiber, 1% ash and 0.2% fat.",
    "price": 18,
    "discountPercentage": 10.23,
    "rating": 4.43,
    "stock": 68,
    "category": "Vegetable",
    "thumbnail": "assets/carrot.png",
    "images": [
      "assets/carrot.png",
      "assets/carrot.png",
      "assets/carrot.png",
      "assets/carrot.png",
      "assets/carrot.png",
    ],
    "favourite": false,
  },
  {
    "id": 9,
    "title": "Lettuce",
    "description":
        "lettuce, (Lactuca sativa), annual leaf vegetable of the aster family (Asteraceae). Most lettuce varieties are eaten fresh and are commonly served as the base of green salads.",
    "price": 21,
    "discountPercentage": 11.83,
    "rating": 4.54,
    "stock": 96,
    "category": "Vegetable",
    "thumbnail": "assets/lettuce.jpg",
    "images": [
      "assets/lettuce.jpg",
      "assets/lettuce.jpg",
      "assets/lettuce.jpg",
      "assets/lettuce.jpg",
      "assets/lettuce.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 10,
    "title": "Tomato",
    "description":
        "They are usually red, scarlet, or yellow, though green and purple varieties do exist, and they vary in shape from almost spherical to oval and elongate to pear-shaped.",
    "price": 50,
    "discountPercentage": 6.18,
    "rating": 4.43,
    "stock": 89,
    "category": "Vegetable",
    "thumbnail": "assets/tomato.jpg",
    "images": [
      "assets/tomato.jpg",
      "assets/tomato.jpg",
      "assets/tomato.jpg",
      "assets/tomato.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 11,
    "title": "Safaid Paplet (White Pomfret)",
    "description":
        "There is no fish like the Pomfret (Paplet) Fish. It is delicious in taste and incredibly healthy. The Pomfret is the preferred choice of fish for elitist and fish lovers. The pomfret is rich in source for Proteins, Calcium, Phosphorus and Iron. You can grill it or fry it or make small pieces to be used in gravy of your choice.",
    "price": 60,
    "discountPercentage": 8.4,
    "rating": 4.26,
    "stock": 65,
    "brand": "Sea Foods",
    "category": "Fishes",
    "thumbnail": "assets/white_paplet.jpg",
    "images": [
       "assets/white_paplet.jpg",
       "assets/white_paplet.jpg",
       "assets/white_paplet.jpg",
       "assets/white_paplet.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 12,
    "title": "Kala Paplet (Black Pomfret)",
    "description": "A cheaper variety to the White Pomfret is the currently available Black Pomfret. Although different in color, but with the has the same taste and is incredibly healthy. The pomfret is rich in source for Proteins, Calcium, Phosphorus and Iron. You can grill it or fry it or make small pieces to be used in gravy of your choice.",
    "price": 40,
    "discountPercentage": 15.66,
    "rating": 4,
    "stock": 52,
    "category": "Fishes",
    "thumbnail": "assets/Black-Paplet.jpg",
    "images": [
      "assets/Black-Paplet.jpg",
      "assets/Black-Paplet.jpg",
      "assets/Black-Paplet.jpg",
      "assets/Black-Paplet.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 13,
    "title": "Jumbo Shrimps",
    "description":
        "Shrimps are similar to Prawns but with limited sizes Fishes and Seafood lovers enjoy Shrimps and are highly appreciative of its taste.",
    "price": 13,
    "discountPercentage": 8.14,
    "rating": 4.59,
    "stock": 61,
    "category": "Fishes",
    "thumbnail": "assets/jumbo-shrimps.jpg",
    "images": [
      "assets/jumbo-shrimps.jpg",
      "assets/jumbo-shrimps.jpg",
      "assets/jumbo-shrimps.jpg",
      "assets/jumbo-shrimps.jpg",
      "assets/jumbo-shrimps.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 14,
    "title": "Saram Fish (Queen Fish)",
    "description":
        "Queen (Saram) fish is available in abundance in the port of Karachi. With their firm flesh and amazing flavor the Queen (saram) fish lends it self to a variety of cooking method including grilling, poaching, frying and baking.",
    "price": 120,
    "discountPercentage": 15.6,
    "rating": 4.21,
    "stock": 114,
    "category": "Fishes",
    "thumbnail": "assets/queen-fish.jpg",
    "images": [
      "assets/queen-fish.jpg",
      "assets/queen-fish.jpg",
      "assets/queen-fish.jpg",
      "assets/queen-fish.jpg",
      ],
    "favourite": false,
  },
  {
    "id": 15,
    "title": "Heera Fish (Red Snapper)",
    "description":
        "Heera Fish is also know as Red Snapper in English. Heera Fish is an exotic fish with sweet, firm texture and immaculate taste. Although Heera fish comes in various colors and sizes but there is only one true Heera fish that is the Lal Heera fish. It is full of healthy benefits including by increasing metabolism, increasing white blood cells and Omega-3 fatty acids",
    "price": 30,
    "discountPercentage": 10.99,
    "rating": 4.7,
    "stock": 105,
    "category": "Fishes",
    "thumbnail": "assets/red-snapper.jpg",
    "images": [
      "assets/red-snapper.jpg",
      "assets/red-snapper.jpg",
      "assets/red-snapper.jpg",
      "assets/red-snapper.jpg",
      "assets/red-snapper.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 16,
    "title": "Chicken",
    "description":
        "Chickens are average-sized fowls, characterized by smaller heads, short beaks and wings, and a round body perched on featherless legs.",
    "price": 30,
    "discountPercentage": 13.31,
    "rating": 4.83,
    "stock": 110,
    "category": "Meats",
    "thumbnail": "assets/chicken.jpg",
    "images": [
    "assets/chicken.jpg",
    "assets/chicken.jpg",
    "assets/chicken.jpg",
    "assets/chicken.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 17,
    "title": "Mutton",
    "description": 
    "Mutton is meat from a sheep over two years old, and has less tender flesh. In general, the darker the colour, the older the animal.",
    "price": 60,
    "discountPercentage": 4.09,
    "rating": 4.52,
    "stock": 78,
    "category": "Meats",
    "thumbnail": "assets/goatbeef.webp",
    "images": [
      "assets/goatbeef.webp",
      "assets/goatbeef.webp",
      "assets/goatbeef.webp",
      "assets/goatbeef.webp",
    ],
    "favourite": false,
  },
    {
    "id": 18,
    "title": "Cow_Beef",
    "description": 
    "Mutton is meat from a sheep over two years old, and has less tender flesh. In general, the darker the colour, the older the animal.",
    "price": 60,
    "discountPercentage": 4.09,
    "rating": 4.52,
    "stock": 78,
    "category": "Meats",
    "thumbnail": "assets/cowbeef.png",
    "images": [
      "assets/cowbeef.png",
      "assets/cowbeef.png",
      "assets/cowbeef.png",
      "assets/cowbeef.png",
    ],
    "favourite": false,
  },
    {
    "id": 19,
    "title": "Camel_Beef",
    "description":
    "The protein content of camel meat ranges from 17.1% to 22.1% (Table 2), with meat from young camels containing similar protein percentages to those found in young cattle, goat, and lamb meats (Kadim et al., 2008). ",
    "price": 55,
    "discountPercentage": 10.68,
    "rating": 4.42,
    "stock": 54,
    "category": "Meats",
    "thumbnail": "assets/camel_Beef.webp",
    "images": [
      "assets/camel_Beef.webp",
      "assets/camel_Beef.webp",
      "assets/camel_Beef.webp",
      "assets/camel_Beef.webp",
    ],
    "favourite": false,
  },
  {
    "id": 20,
    "title": "Sheep_Beef",
    "description":
        "Sheep meat is a globally important commodity. Sheep meat is sourced from a wide range of production systems that can determine muscle quality, meat composition, and nutritional characteristics – being rich in several vitamins, minerals, and essential polyunsaturated fatty acids.",
    "price": 70,
    "discountPercentage": 16.99,
    "rating": 4.06,
    "stock": 140,
    "category": "Meats",
    "thumbnail": "assets/sheep.jpg",
    "images": [
      "assets/sheep.jpg",
      "assets/sheep.jpg",
      "assets/sheep.jpg",
      "assets/sheep.jpg",
      "assets/sheep.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 21,
    "title": "- Sugar",
    "description": "Sugar is a term that includes all sweet carbohydrates, although the term is most often used to describe sucrose or table sugar, a 'double sugar'.",
    "price": 25,
    "discountPercentage": 4.81,
    "rating": 4.44,
    "stock": 133,
    "brand": "Saaf & Khaas",
    "category": "groceries",
    "thumbnail": "assets/sugar.webp",
    "images": [
      "assets/sugar.webp",
      "assets/sugar.webp",
      "assets/sugar.webp"
    ],
    "favourite": false,
  },
  {
    "id": 22,
        "title": "- Daal Masoor 500 grams",
    "description": "Fine quality Branded Product Keep in a cool and dry place",
    "price": 20,
    "discountPercentage": 4.81,
    "rating": 4.44,
    "stock": 133,
    "brand": "Saaf & Khaas",
    "category": "groceries",
    "thumbnail": "assets/daal_masoor.jpg",
    "images": [
      "assets/daal_masoor.jpg",
      "assets/daal_masoor.jpg",
      "assets/daal_masoor.jpg",
    ],
    "favourite": false,
},
  {
    "id": 23,
    "title": "Super Fine Atta 10kg (Laminated)",
    "description": "Product details of Bake Parlor Super Fine Atta 10kg (Laminated)",
    "price": 14,
    "discountPercentage": 15.58,
    "rating": 4.57,
    "stock": 146,
    "brand": "Bake Parlor Big",
    "category": "groceries",
    "thumbnail": "assets/fine_ata.webp",
    "images": [
      "assets/fine_ata.webp",
      "assets/fine_ata.webp",
      "assets/fine_ata.webp",
    ],
    "favourite": false,  
    },
  {
    "id": 24,
    "title": "Kisan oil 5 litre bottle",
    "description":
        "No cholesterol. Like other vegetable fats, canola oil is free of cholesterol & contains vitamins E and K",
    "price": 46,
    "discountPercentage": 16.8,
    "rating": 4.94,
    "stock": 113,
    "brand": "KIsan Oil",
    "category": "groceries",
    "thumbnail": "assets/oil.jpg",
    "images": [
      "assets/oil.jpg",
      "assets/oil.jpg",
      "assets/oil.jpg",
      "assets/oil.jpg",
      "assets/oil.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 25,
    "title": "Tapal Danedar Tea",
    "description":
    "Tapal Danedar Black Loose Tea 385G Tapal Tea Is Made With Premium Tea Leaves Hand-Picked From The Best Gardens In The World",
    "price": 10,
    "discountPercentage": 16.8,
    "rating": 4.94,
    "stock": 113,
    "brand": "Tapal danedar",
    "category": "groceries",
    "thumbnail": "assets/tapal.webp",
    "images": [
      "assets/tapal.webp",
      "assets/tapal.webp",
      "assets/tapal.webp",
      "assets/tapal.webp",
      "assets/tapal.webp",
    ],
    "favourite": false,
    },
  {
    "id": 26,
    "title": "Plant Hanger For Home",
    "description":
        "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
    "price": 41,
    "discountPercentage": 17.86,
    "rating": 4.08,
    "stock": 131,
    "brand": "Boho Decor",
    "category": "home-decoration",
    "thumbnail": "https://i.dummyjson.com/data/products/26/thumbnail.jpg",
    "images": [
      "https://i.dummyjson.com/data/products/26/1.jpg",
      "https://i.dummyjson.com/data/products/26/2.jpg",
      "https://i.dummyjson.com/data/products/26/3.jpg",
      "https://i.dummyjson.com/data/products/26/4.jpg",
      "https://i.dummyjson.com/data/products/26/5.jpg",
      "https://i.dummyjson.com/data/products/26/thumbnail.jpg"
    ],
    "favourite": false,
  },
  {
    "id": 27,
    "title": "Flying Wooden Bird",
    "description":
        "Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm",
    "price": 51,
    "discountPercentage": 15.58,
    "rating": 4.41,
    "stock": 17,
    "brand": "Flying Wooden",
    "category": "home-decoration",
    "thumbnail": "https://i.dummyjson.com/data/products/27/thumbnail.webp",
    "images": [
      "https://i.dummyjson.com/data/products/27/1.jpg",
      "https://i.dummyjson.com/data/products/27/2.jpg",
      "https://i.dummyjson.com/data/products/27/3.jpg",
      "https://i.dummyjson.com/data/products/27/4.jpg",
      "https://i.dummyjson.com/data/products/27/thumbnail.webp"
    ],
    "favourite": false,
  },
  {
    "id": 28,
    "title": "3D Embellishment Art Lamp",
    "description":
        "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)",
    "price": 20,
    "discountPercentage": 16.49,
    "rating": 4.82,
    "stock": 54,
    "brand": "LED Lights",
    "category": "home-decoration",
    "thumbnail": "https://i.dummyjson.com/data/products/28/thumbnail.jpg",
    "images": [
      "https://i.dummyjson.com/data/products/28/1.jpg",
      "https://i.dummyjson.com/data/products/28/2.jpg",
      "https://i.dummyjson.com/data/products/28/3.png",
      "https://i.dummyjson.com/data/products/28/4.jpg",
      "https://i.dummyjson.com/data/products/28/thumbnail.jpg"
    ],
    "favourite": false,
  },
  {
    "id": 29,
    "title": "Handcraft Chinese style",
    "description":
        "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate",
    "price": 60,
    "discountPercentage": 15.34,
    "rating": 4.44,
    "stock": 7,
    "brand": "luxury palace",
    "category": "home-decoration",
    "thumbnail": "https://i.dummyjson.com/data/products/29/thumbnail.webp",
    "images": [
      "https://i.dummyjson.com/data/products/29/1.jpg",
      "https://i.dummyjson.com/data/products/29/2.jpg",
      "https://i.dummyjson.com/data/products/29/3.webp",
      "https://i.dummyjson.com/data/products/29/4.webp",
      "https://i.dummyjson.com/data/products/29/thumbnail.webp"
    ],
    "favourite": false,
  },
  {
    "id": 30,
    "title": "Key Holder",
    "description":
        "Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality",
    "price": 30,
    "discountPercentage": 2.92,
    "rating": 4.92,
    "stock": 54,
    "brand": "Golden",
    "category": "home-decoration",
    "thumbnail": "https://i.dummyjson.com/data/products/30/thumbnail.jpg",
    "images": [
      "https://i.dummyjson.com/data/products/30/1.jpg",
      "https://i.dummyjson.com/data/products/30/2.jpg",
      "https://i.dummyjson.com/data/products/30/3.jpg",
      "https://i.dummyjson.com/data/products/30/thumbnail.jpg"
    ],
    "favourite": false,
  }
];

//

//

//

//
List<Map> productCategories = [
  {
    "id": 1,
    "title": "Orange",
    "description": "The orange is a usually round or oval citrus; its rind and flesh are generally orange, except the varieties of red pulp. The edible part of the orange is the flesh, consumed in fresh or in juice.",
    "price": 10,
    "discountPercentage": 25,
    "rating": 4.5,
    "stock": 100,
    "category": "Fruits",
    "thumbnail": "assets/fruits.jpg",

    "images": [
      "assets/orange.png",
      "assets/orange.png",
      "assets/orange.png",
      "assets/orange.png",
    ],
    "favourite": false,
  },
  {
    "id": 6,
    "title": "Potato",
    "description":
        " The potato is one of some 150 tuber-bearing species of the genus Solanum (a tuber is the swollen end of an underground stem)",
    "price": 12,
    "discountPercentage": 11.02,
    "rating": 4.57,
    "stock": 83,
    "category": "Vegetables",
    "thumbnail": "assets/vegetable.jpg",
    "images": [
      "assets/patoto.webp",
      "assets/patoto.webp",
      "assets/patoto.webp",
      "assets/patoto.webp",
    ],
    "favourite": false,
  },
  {
    "id": 11,
    "title": "Safaid Paplet (White Pomfret)",
    "description":
        "There is no fish like the Pomfret (Paplet) Fish. It is delicious in taste and incredibly healthy. The Pomfret is the preferred choice of fish for elitist and fish lovers. The pomfret is rich in source for Proteins, Calcium, Phosphorus and Iron. You can grill it or fry it or make small pieces to be used in gravy of your choice.",
    "price": 60,
    "discountPercentage": 8.4,
    "rating": 4.26,
    "stock": 65,
    "brand": "Sea Foods",
    "category": "Fishes",
    "thumbnail": "assets/fishes.webp",
    "images": [
       "assets/white_paplet.jpg",
       "assets/white_paplet.jpg",
       "assets/white_paplet.jpg",
       "assets/white_paplet.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 16,
    "title": "Chicken",
    "description":
        "Chickens are average-sized fowls, characterized by smaller heads, short beaks and wings, and a round body perched on featherless legs.",
    "price": 30,
    "discountPercentage": 13.31,
    "rating": 4.83,
    "stock": 110,
    "category": "Meats",
    "thumbnail": "assets/meat.jpg",
    "images": [
    "assets/chicken.jpg",
    "assets/chicken.jpg",
    "assets/chicken.jpg",
    "assets/chicken.jpg",
    ],
    "favourite": false,
  },
 
  {
    "id": 21,
    "title": "- Sugar",
    "description": "Sugar is a term that includes all sweet carbohydrates, although the term is most often used to describe sucrose or table sugar, a 'double sugar'.",
    "price": 25,
    "discountPercentage": 4.81,
    "rating": 4.44,
    "stock": 133,
    "brand": "Saaf & Khaas",
    "category": "groceries",
    "thumbnail": "assets/grocery.webp",
    "images": [
      "assets/sugar.webp",
      "assets/sugar.webp",
      "assets/sugar.webp",
      "assets/sugar.webp"
    ],
    "favourite": false,
  },
];

//
//
List<Map> fruits = [
  {
        "id": 1,
    "title": "Orange",
    "description": "The orange is a usually round or oval citrus; its rind and flesh are generally orange, except the varieties of red pulp. The edible part of the orange is the flesh, consumed in fresh or in juice.",
    "price": 10,
    "discountPercentage": 25,
    "rating": 4.5,
    "stock": 100,
    "category": "Fruits",
    "thumbnail": "assets/orange.png",
    "images": [
      "assets/orange.png",     
      "assets/orange.png",
      "assets/orange.png",
      "assets/orange.png",
    ],

    "favourite": false,
  },
  {
    "id": 2,
    "title": "Apple",
    "description": "Apples are among the world's most popular fruits. They grow on the apple tree (Malus domestica), originally from Central Asia. Apples are high in fiber, vitamin C, and various antioxidants.",
    "price": 15,
    "discountPercentage": 15,
    "rating": 4.5,
    "stock": 95,
    "category": "Fruits",
    "thumbnail": "assets/apple.jpg",
    "images": [
      "assets/apple.jpg",
      "assets/apple.jpg",
      "assets/apple.jpg",
      "assets/apple.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 3,
    "title": "Mango",
    "description": "The immature fruit has green skin that gradually turns yellow, orange, purple, red, or combinations of these colors as the fruit matures. Mature fruit has a characteristic fragrance and a smooth, thin, tough skin. The flesh of ripe mangos is pale yellow to orange. The flesh is juicy, sweet, and sometimes fibrous.",
    "price": 30,
    "discountPercentage": 05,
    "rating": 4.5,
    "stock": 95,
    "category": "Fruits",
    "thumbnail": "assets/mango.png",
    "images": [
      "assets/mango.png",
      "assets/mango.png",
      "assets/mango.png",
      "assets/mango.png",
    ],
    "favourite": false,
  },
  {
    "id": 4,
    "title": "Banana",
    "description": "Bananas are a healthy source of fiber, potassium, vitamin B6, vitamin C, and various antioxidants and phytonutrients.",
    "price": 280,
    "discountPercentage": 17.91,
    "rating": 4.3,
    "stock": 123,
    "category": "Fruits",
    "thumbnail": "assets/banana.jpg",
    "images": [
      "assets/banana.jpg",
      "assets/banana.jpg",
      "assets/banana.jpg",
      "assets/banana.jpg",
      "assets/banana.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 5,
    "title": "Peach",
    "description":
        "Peaches are a fuzzy fruit native to northwest China. They are a member of the stone fruit family, which means that their flesh surrounds one large middle seed",
    "price": 499,
    "discountPercentage": 10.58,
    "rating": 4.09,
    "stock": 32,
    "category": "Fruits",
    "thumbnail": "assets/peach.jpg",
    "images": [
      "assets/peach.jpg",
      "assets/peach.jpg",
      "assets/peach.jpg",
    ],
    "favourite": false,
  },
];

//
//
List<Map> vegetable= [
  {
    "id": 6,
    "title": "Potato",
    "description":
        " The potato is one of some 150 tuber-bearing species of the genus Solanum (a tuber is the swollen end of an underground stem)",
    "price": 12,
    "discountPercentage": 11.02,
    "rating": 4.57,
    "stock": 83,
    "category": "Vegetables",
    "thumbnail": "assets/patoto.webp",
    "images": [
      "assets/patoto.webp",
      "assets/patoto.webp",
      "assets/patoto.webp",
      "assets/patoto.webp",
    ],
    "favourite": false,
  },
  {
    "id": 7,
    "title": "Onion",
    "description":
        "Onions belong to the Allium family of plants, which also includes chives, garlic, and leeks.",
    "price": 14,
    "discountPercentage": 4.15,
    "rating": 4.25,
    "stock": 354,
    "category": "Vegetables",
    "thumbnail": "assets/onion.webp",
    "images": [
      "assets/onion.webp",
      "assets/onion.webp",
      "assets/onion.webp",
      "assets/onion.webp",
    ],
    "favourite": false,
  },
  {
    "id": 8,
    "title": "Carrot",
    "description":
        "Raw carrots are 88% water, 9% carbohydrates, 0.9% protein, 2.8% dietary fiber, 1% ash and 0.2% fat.",
    "price": 18,
    "discountPercentage": 10.23,
    "rating": 4.43,
    "stock": 68,
    "category": "Vegetable",
    "thumbnail": "assets/carrot.png",
    "images": [
      "assets/carrot.png",
      "assets/carrot.png",
      "assets/carrot.png",
      "assets/carrot.png",
      "assets/carrot.png",
    ],
    "favourite": false,
  },
  {
    "id": 9,
    "title": "Lettuce",
    "description":
        "lettuce, (Lactuca sativa), annual leaf vegetable of the aster family (Asteraceae). Most lettuce varieties are eaten fresh and are commonly served as the base of green salads.",
    "price": 21,
    "discountPercentage": 11.83,
    "rating": 4.54,
    "stock": 96,
    "category": "Vegetable",
    "thumbnail": "assets/lettuce.jpg",
    "images": [
      "assets/lettuce.jpg",
      "assets/lettuce.jpg",
      "assets/lettuce.jpg",
      "assets/lettuce.jpg",
      "assets/lettuce.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 10,
    "title": "Tomato",
    "description":
        "They are usually red, scarlet, or yellow, though green and purple varieties do exist, and they vary in shape from almost spherical to oval and elongate to pear-shaped.",
    "price": 50,
    "discountPercentage": 6.18,
    "rating": 4.43,
    "stock": 89,
    "category": "Vegetable",
    "thumbnail": "assets/tomato.jpg",
    "images": [
      "assets/tomato.jpg",
      "assets/tomato.jpg",
      "assets/tomato.jpg",
      "assets/tomato.jpg",
    ],
    "favourite": false,
  },
];
//
//
List<Map> fishes= [
  {
    "id": 11,
    "title": "Safaid Paplet (White Pomfret)",
    "description":
        "There is no fish like the Pomfret (Paplet) Fish. It is delicious in taste and incredibly healthy. The Pomfret is the preferred choice of fish for elitist and fish lovers. The pomfret is rich in source for Proteins, Calcium, Phosphorus and Iron. You can grill it or fry it or make small pieces to be used in gravy of your choice.",
    "price": 60,
    "discountPercentage": 8.4,
    "rating": 4.26,
    "stock": 65,
    "brand": "Sea Foods",
    "category": "Fishes",
    "thumbnail": "assets/white_paplet.jpg",
    "images": [
       "assets/white_paplet.jpg",
       "assets/white_paplet.jpg",
       "assets/white_paplet.jpg",
       "assets/white_paplet.jpg",
       "assets/white_paplet.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 12,
    "title": "Kala Paplet (Black Pomfret)",
    "description": "A cheaper variety to the White Pomfret is the currently available Black Pomfret. Although different in color, but with the has the same taste and is incredibly healthy. The pomfret is rich in source for Proteins, Calcium, Phosphorus and Iron. You can grill it or fry it or make small pieces to be used in gravy of your choice.",
    "price": 40,
    "discountPercentage": 15.66,
    "rating": 4,
    "stock": 52,
    "category": "Fishes",
    "thumbnail": "assets/Black-Paplet.jpg",
    "images": [
      "assets/Black-Paplet.jpg",
      "assets/Black-Paplet.jpg",
      "assets/Black-Paplet.jpg",
      "assets/Black-Paplet.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 13,
    "title": "Jumbo Shrimps",
    "description":
        "Shrimps are similar to Prawns but with limited sizes Fishes and Seafood lovers enjoy Shrimps and are highly appreciative of its taste.",
    "price": 13,
    "discountPercentage": 8.14,
    "rating": 4.59,
    "stock": 61,
    "category": "Fishes",
    "thumbnail": "assets/jumbo-shrimps.jpg",
    "images": [
      "assets/jumbo-shrimps.jpg",
      "assets/jumbo-shrimps.jpg",
      "assets/jumbo-shrimps.jpg",
      "assets/jumbo-shrimps.jpg",
      "assets/jumbo-shrimps.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 14,
    "title": "Saram Fish (Queen Fish)",
    "description":
        "Queen (Saram) fish is available in abundance in the port of Karachi. With their firm flesh and amazing flavor the Queen (saram) fish lends it self to a variety of cooking method including grilling, poaching, frying and baking.",
    "price": 120,
    "discountPercentage": 15.6,
    "rating": 4.21,
    "stock": 114,
    "category": "Fishes",
    "thumbnail": "assets/queen-fish.jpg",
    "images": [
      "assets/queen-fish.jpg",
      "assets/queen-fish.jpg",
      "assets/queen-fish.jpg",
      "assets/queen-fish.jpg",
      ],
    "favourite": false,
  },
  {
    "id": 15,
    "title": "Heera Fish (Red Snapper)",
    "description":
        "Heera Fish is also know as Red Snapper in English. Heera Fish is an exotic fish with sweet, firm texture and immaculate taste. Although Heera fish comes in various colors and sizes but there is only one true Heera fish that is the Lal Heera fish. It is full of healthy benefits including by increasing metabolism, increasing white blood cells and Omega-3 fatty acids",
    "price": 30,
    "discountPercentage": 10.99,
    "rating": 4.7,
    "stock": 105,
    "category": "Fishes",
    "thumbnail": "assets/red-snapper.jpg",
    "images": [
      "assets/red-snapper.jpg",
      "assets/red-snapper.jpg",
      "assets/red-snapper.jpg",
      "assets/red-snapper.jpg",
      "assets/red-snapper.jpg",
    ],
    "favourite": false,
  },
];
//
//
List<Map> meat = [
  {
    "id": 16,
    "title": "Chicken",
    "description":
        "Chickens are average-sized fowls, characterized by smaller heads, short beaks and wings, and a round body perched on featherless legs.",
    "price": 30,
    "discountPercentage": 13.31,
    "rating": 4.83,
    "stock": 110,
    "category": "Meats",
    "thumbnail": "assets/chicken.jpg",
    "images": [
    "assets/chicken.jpg",
    "assets/chicken.jpg",
    "assets/chicken.jpg",
    "assets/chicken.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 17,
    "title": "Mutton",
    "description": 
    "Mutton is meat from a sheep over two years old, and has less tender flesh. In general, the darker the colour, the older the animal.",
    "price": 60,
    "discountPercentage": 4.09,
    "rating": 4.52,
    "stock": 78,
    "category": "Meats",
    "thumbnail": "assets/goatbeef.webp",
    "images": [
      "assets/goatbeef.webp",
      "assets/goatbeef.webp",
      "assets/goatbeef.webp",
      "assets/goatbeef.webp",
    ],
    "favourite": false,
  },
  {
    "id": 18,
    "title": "Cow_Beef",
    "description":
    "Beef is mainly composed of saturated and monounsaturated fat, present in approximately equal amounts.",
    "price": 45,
    "discountPercentage": 13.1,
    "rating": 4.56,
    "stock": 88,
    "category": "Meats",
    "thumbnail": "assets/cowbeef.png",
    "images": [
      "assets/cowbeef.png",
      "assets/cowbeef.png",
      "assets/cowbeef.png",
      "assets/cowbeef.png",
    ],
    "favourite": false,
  },
  {
    "id": 19,
    "title": "Camel_Beef",
    "description":
    "The protein content of camel meat ranges from 17.1% to 22.1% (Table 2), with meat from young camels containing similar protein percentages to those found in young cattle, goat, and lamb meats (Kadim et al., 2008). ",
    "price": 55,
    "discountPercentage": 10.68,
    "rating": 4.42,
    "stock": 54,
    "category": "Meats",
    "thumbnail": "assets/camel_Beef.webp",
    "images": [
      "assets/camel_Beef.webp",
      "assets/camel_Beef.webp",
      "assets/camel_Beef.webp",
      "assets/camel_Beef.webp",
    ],
    "favourite": false,
  },
  {
    "id": 20,
    "title": "Sheep_Beef",
    "description":
        "Sheep meat is a globally important commodity. Sheep meat is sourced from a wide range of production systems that can determine muscle quality, meat composition, and nutritional characteristics – being rich in several vitamins, minerals, and essential polyunsaturated fatty acids.",
    "price": 70,
    "discountPercentage": 16.99,
    "rating": 4.06,
    "stock": 140,
    "category": "Meats",
    "thumbnail": "assets/sheep.jpg",
    "images": [
      "assets/sheep.jpg",
      "assets/sheep.jpg",
      "assets/sheep.jpg",
      "assets/sheep.jpg",
      "assets/sheep.jpg",
    ],
    "favourite": false,
  },
];
//
//

List<Map> groceries = [
    {
    "id": 21,
    "title": "- Sugar",
    "description": "Sugar is a term that includes all sweet carbohydrates, although the term is most often used to describe sucrose or table sugar, a 'double sugar'.",
    "price": 25,
    "discountPercentage": 4.81,
    "rating": 4.44,
    "stock": 133,
    "brand": "Saaf & Khaas",
    "category": "groceries",
    "thumbnail": "assets/sugar.webp",
    "images": [
      "assets/sugar.webp",
      "assets/sugar.webp",
      "assets/sugar.webp"
    ],
    "favourite": false,
  },
  {
    "id": 22,
    "title": "Daal Masoor 500 grams",
    "description": "Fine quality Branded Product Keep in a cool and dry place",
    "price": 20,
    "discountPercentage": 4.81,
    "rating": 4.44,
    "stock": 133,
    "brand": "Saaf & Khaas",
    "category": "groceries",
    "thumbnail": "assets/daal_masoor.jpg",
    "images": [
      "assets/daal_masoor.jpg",
      "assets/daal_masoor.jpg",
      "assets/daal_masoor.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 23,
    "title": "Super Fine Atta 10kg (Laminated)",
    "description": "Product details of Bake Parlor Super Fine Atta 10kg (Laminated)",
    "price": 14,
    "discountPercentage": 15.58,
    "rating": 4.57,
    "stock": 146,
    "brand": "Bake Parlor Big",
    "category": "groceries",
    "thumbnail": "assets/fine_ata.webp",
    "images": [
      "assets/fine_ata.webp",
      "assets/fine_ata.webp",
      "assets/fine_ata.webp",
    ],
    "favourite": false,
  },
  {
    "id": 24,
    "title": "Kisan oil 5 litre bottle",
    "description":
        "No cholesterol. Like other vegetable fats, canola oil is free of cholesterol & contains vitamins E and K",
    "price": 46,
    "discountPercentage": 16.8,
    "rating": 4.94,
    "stock": 113,
    "brand": "KIsan Oil",
    "category": "groceries",
    "thumbnail": "assets/oil.jpg",
    "images": [
      "assets/oil.jpg",
      "assets/oil.jpg",
      "assets/oil.jpg",
      "assets/oil.jpg",
      "assets/oil.jpg",
    ],
    "favourite": false,
  },
  {
    "id": 25,
    "title": "Tapal Danedar Tea",
    "description":
    "Tapal Danedar Black Loose Tea 385G Tapal Tea Is Made With Premium Tea Leaves Hand-Picked From The Best Gardens In The World",
    "price": 10,
    "discountPercentage": 16.8,
    "rating": 4.94,
    "stock": 113,
    "brand": "Tapal danedar",
    "category": "groceries",
    "thumbnail": "assets/tapal.webp",
    "images": [
      "assets/tapal.webp",
      "assets/tapal.webp",
      "assets/tapal.webp",
      "assets/tapal.webp",
      "assets/tapal.webp",
    ],
    "favourite": false,
  },
];
//
//
List<Map> homeDecoration = [
  {
    "id": 26,
    "title": "Plant Hanger For Home",
    "description":
        "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
    "price": 41,
    "discountPercentage": 17.86,
    "rating": 4.08,
    "stock": 131,
    "brand": "Boho Decor",
    "category": "home-decoration",
    "thumbnail": "https://i.dummyjson.com/data/products/26/thumbnail.jpg",
    "images": [
      "https://i.dummyjson.com/data/products/26/1.jpg",
      "https://i.dummyjson.com/data/products/26/2.jpg",
      "https://i.dummyjson.com/data/products/26/3.jpg",
      "https://i.dummyjson.com/data/products/26/4.jpg",
      "https://i.dummyjson.com/data/products/26/5.jpg",
      "https://i.dummyjson.com/data/products/26/thumbnail.jpg"
    ],
    "favourite": false,
  },
  {
    "id": 27,
    "title": "Flying Wooden Bird",
    "description":
        "Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm",
    "price": 51,
    "discountPercentage": 15.58,
    "rating": 4.41,
    "stock": 17,
    "brand": "Flying Wooden",
    "category": "home-decoration",
    "thumbnail": "https://i.dummyjson.com/data/products/27/thumbnail.webp",
    "images": [
      "https://i.dummyjson.com/data/products/27/1.jpg",
      "https://i.dummyjson.com/data/products/27/2.jpg",
      "https://i.dummyjson.com/data/products/27/3.jpg",
      "https://i.dummyjson.com/data/products/27/4.jpg",
      "https://i.dummyjson.com/data/products/27/thumbnail.webp"
    ],
    "favourite": false,
  },
  {
    "id": 28,
    "title": "3D Embellishment Art Lamp",
    "description":
        "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)",
    "price": 20,
    "discountPercentage": 16.49,
    "rating": 4.82,
    "stock": 54,
    "brand": "LED Lights",
    "category": "home-decoration",
    "thumbnail": "https://i.dummyjson.com/data/products/28/thumbnail.jpg",
    "images": [
      "https://i.dummyjson.com/data/products/28/1.jpg",
      "https://i.dummyjson.com/data/products/28/2.jpg",
      "https://i.dummyjson.com/data/products/28/3.png",
      "https://i.dummyjson.com/data/products/28/4.jpg",
      "https://i.dummyjson.com/data/products/28/thumbnail.jpg"
    ],
    "favourite": false,
  },
  {
    "id": 29,
    "title": "Handcraft Chinese style",
    "description":
        "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate",
    "price": 60,
    "discountPercentage": 15.34,
    "rating": 4.44,
    "stock": 7,
    "brand": "luxury palace",
    "category": "home-decoration",
    "thumbnail": "https://i.dummyjson.com/data/products/29/thumbnail.webp",
    "images": [
      "https://i.dummyjson.com/data/products/29/1.jpg",
      "https://i.dummyjson.com/data/products/29/2.jpg",
      "https://i.dummyjson.com/data/products/29/3.webp",
      "https://i.dummyjson.com/data/products/29/4.webp",
      "https://i.dummyjson.com/data/products/29/thumbnail.webp"
    ],
    "favourite": false,
  },
  {
    "id": 30,
    "title": "Key Holder",
    "description":
        "Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality",
    "price": 30,
    "discountPercentage": 2.92,
    "rating": 4.92,
    "stock": 54,
    "brand": "Golden",
    "category": "home-decoration",
    "thumbnail": "https://i.dummyjson.com/data/products/30/thumbnail.jpg",
    "images": [
      "https://i.dummyjson.com/data/products/30/1.jpg",
      "https://i.dummyjson.com/data/products/30/2.jpg",
      "https://i.dummyjson.com/data/products/30/3.jpg",
      "https://i.dummyjson.com/data/products/30/thumbnail.jpg"
    ],
    "favourite": false,
  }
];

List categories = [
  fruits,
  vegetable,
  fishes,
  meat,
  groceries,
];


List prodsImgs = [
  [
      "assets/orange.png",
      "assets/orange.png",
      "assets/orange.png",
      "assets/orange.png",

  ],
  [
      "assets/apple.jpg",
      "assets/apple.jpg",
      "assets/apple.jpg",
      "assets/apple.jpg",
  ],
  [
      "assets/mango.png",
      "assets/mango.png",
      "assets/mango.png",
      "assets/mango.png",

  ],
  [
    "assets/banana.jpg",
    "assets/banana.jpg",
    "assets/banana.jpg",
    "assets/banana.jpg",
    "assets/banana.jpg",
  ],
  [
    "assets/peach.jpg",
    "assets/peach.jpg",
    "assets/peach.jpg",
  ],
  [
    "assets/patoto.webp",
    "assets/patoto.webp",
    "assets/patoto.webp",
    "assets/patoto.webp",
  ],
  [
    "assets/onion.webp",
    "assets/onion.webp",
    "assets/onion.webp",
    "assets/onion.webp",
  ],
  [
    "assets/carrot.png",
    "assets/carrot.png",
    "assets/carrot.png",
    "assets/carrot.png",
    "assets/carrot.png",
  ],
  [
    "assets/lettuce.jpg",
    "assets/lettuce.jpg",
    "assets/lettuce.jpg",
    "assets/lettuce.jpg",
    "assets/lettuce.jpg",
  ],
  [
    "assets/tomato.jpg",
    "assets/tomato.jpg",
    "assets/tomato.jpg",
    "assets/tomato.jpg",
  ],
  [
    "assets/white_paplet.jpg",
    "assets/white_paplet.jpg",
    "assets/white_paplet.jpg",
    "assets/white_paplet.jpg",
    "assets/white_paplet.jpg",


  ],
  [
    "assets/Black-Paplet.jpg",
    "assets/Black-Paplet.jpg",
    "assets/Black-Paplet.jpg",
    "assets/Black-Paplet.jpg",
    "assets/Black-Paplet.jpg",
  ],
  [
    "assets/jumbo-shrimps.jpg",
    "assets/jumbo-shrimps.jpg",
    "assets/jumbo-shrimps.jpg",
    "assets/jumbo-shrimps.jpg",
    "assets/jumbo-shrimps.jpg",
  ],
  [
    "assets/queen-fish.jpg",
    "assets/queen-fish.jpg",
    "assets/queen-fish.jpg",
    "assets/queen-fish.jpg",
  ],
  [
    "assets/red-snapper.jpg",
    "assets/red-snapper.jpg",
    "assets/red-snapper.jpg",
    "assets/red-snapper.jpg",
    "assets/red-snapper.jpg",
    ],
  [
    "assets/chicken.jpg",
    "assets/chicken.jpg",
    "assets/chicken.jpg",
    "assets/chicken.jpg",
  ],
  [
    "assets/goatbeef.webp",
    "assets/goatbeef.webp",
    "assets/goatbeef.webp",
    "assets/goatbeef.webp",
  ],
  [
    "assets/cowbeef/png",
    "assets/cowbeef/png",
    "assets/cowbeef/png",
    "assets/cowbeef/png",
  ],
  [
    "assets/camel_Beef.webp",
    "assets/camel_Beef.webp",
    "assets/camel_Beef.webp",
    "assets/camel_Beef.webp",
  ],
  [
    "assets/sheep.jpg",
    "assets/sheep.jpg",
    "assets/sheep.jpg",
    "assets/sheep.jpg",
    "assets/sheep.jpg",

  ],
  [
    "assets/sugar.webp",
    "assets/sugar.webp",
    "assets/sugar.webp",
  ],
  [
    "assets/daal_masoor.jpg",
    "assets/daal_masoor.jpg",
    "assets/daal_masoor.jpg",
    "assets/daal_masoor.jpg",
  ],
  [
    "assets/fine_ata.webp",
    "assets/fine_ata.webp",
    "assets/fine_ata.webp",
    "assets/fine_ata.webp",
  ],
  [
    "assets/oil.jpg",
    "assets/oil.jpg",
    "assets/oil.jpg",
    "assets/oil.jpg",
    "assets/oil.jpg",
    ],
  [
      "assets/tapal.webp",
      "assets/tapal.webp",
      "assets/tapal.webp",
      "assets/tapal.webp",
      "assets/tapal.webp",
    ],
  [
    "https://i.dummyjson.com/data/products/26/1.jpg",
    "https://i.dummyjson.com/data/products/26/2.jpg",
    "https://i.dummyjson.com/data/products/26/3.jpg",
    "https://i.dummyjson.com/data/products/26/4.jpg",
    "https://i.dummyjson.com/data/products/26/5.jpg",
    "https://i.dummyjson.com/data/products/26/thumbnail.jpg"
  ],
  [
    "https://i.dummyjson.com/data/products/27/1.jpg",
    "https://i.dummyjson.com/data/products/27/2.jpg",
    "https://i.dummyjson.com/data/products/27/3.jpg",
    "https://i.dummyjson.com/data/products/27/4.jpg",
    "https://i.dummyjson.com/data/products/27/thumbnail.webp"
  ],
  [
    "https://i.dummyjson.com/data/products/28/1.jpg",
    "https://i.dummyjson.com/data/products/28/2.jpg",
    "https://i.dummyjson.com/data/products/28/3.png",
    "https://i.dummyjson.com/data/products/28/4.jpg",
    "https://i.dummyjson.com/data/products/28/thumbnail.jpg"
  ],
  [
    "https://i.dummyjson.com/data/products/29/1.jpg",
    "https://i.dummyjson.com/data/products/29/2.jpg",
    "https://i.dummyjson.com/data/products/29/3.webp",
    "https://i.dummyjson.com/data/products/29/4.webp",
    "https://i.dummyjson.com/data/products/29/thumbnail.webp"
  ],
  [
    "https://i.dummyjson.com/data/products/30/1.jpg",
    "https://i.dummyjson.com/data/products/30/2.jpg",
    "https://i.dummyjson.com/data/products/30/3.jpg",
    "https://i.dummyjson.com/data/products/30/thumbnail.jpg"
  ],
];
// print(images[0][1]);
// items to add in dart
List cartItems = [];

// for subtotal price
List subtotalPrice = [];

//favourites items will be stored in this list
List favouriteList = [];

bool isFavourite = false;

// items will be saved/popped from cartItems to here in orderList after completing payment
List orderList = [];
